## Linear Algebra Quiz #1

![title](./img/1_0.jpeg)

We strongly suggest working with numpy :)

In [3]:
#Do your imports here
import numpy as np

Video pt. 1: https://www.loom.com/share/12b5b0799f8f46cbae9973c74818554c

![title](./img/1_1.png)

In [1]:
# type a function that given a 3_dimensional vector it is able to calculate its magnitude

def magnitude_3(a,b,c):
    
    X = [a, b, c]
    
    return np.linalg.norm(X)


In [4]:
magnitude_3(1,2,3)

3.7416573867739413

In [8]:
# type a function that given a n_dimensional vector it is able to calculate its magnitude
# A couple of ideas, multiple arguments in the function https://docs.python.org/3/library/argparse.html
# And if you are doing this from a jupyter notebook, you can also try to promt the user for an input  

def magnitude_complete(*args):#inputs
    
    X = []
    
    for arg in args:
        X.append(arg)
    return np.linalg.norm(X)

In [9]:
magnitude_complete(1,2,3,4,5)

7.416198487095663

uncomment the following line when you are ready to test

In [10]:
assert magnitude_complete(1) == 1.0
assert magnitude_complete(1,2) >= 2.236
assert magnitude_complete(1,2,3) >= 3.74
assert magnitude_complete(1,2,3,4,5) >= 5.477
assert magnitude_complete(1,2,3,4,5) >= 7.416

![title](./img/1_2.png)

Video pt. 2: https://www.loom.com/share/3b5adfc80bb6454286fb53dad5ebaffa

In [11]:
def magnitude_vectors(a, b):
    #checks that size is equal
    a = np.array(a)
    b = np.array(b)
    a_size = a.size
    b_size = b.size
    
    try:
        a_size == b_size
        a_b_sum = a + b
        return np.linalg.norm(a_b_sum)
    
    except:
        #print('Vectors are different dimensions {} and {}'.format(a_size, b_size))
        print(f'Vectors are different dimensions {a_size} and {b_size}')
    #returns the magnitude

In [13]:
a = np.array([5, 1])
b = np.array([-4,-1])
print(magnitude_vectors(a, b))
# but also 
magnitude_vectors([5, 1], [-4, -1])

1.0


1.0

Video pt. 3: https://www.loom.com/share/54db0b8439ea4cc1879af8de78a67b97

![title](./img/1_3.png)

In [14]:
def direction_vectors(a, b):
    a = np.array(a)
    b = np.array(b)
    a_size = a.size
    b_size = b.size
    
    try:
        #checks that size is equal
        a_size == b_size
    
        #returns the direction
        a_b_sum = a + b
        
        return a_b_sum
    
    except:
        print('Vectors are different dimensions {} and {}'.format(a_size, b_size))

In [15]:
direction_vectors(a, b)

array([1, 0])

In [13]:
# or if you want to do it all in one batch:
def magdir_vectors(a, b):
    #checks that size is equal
    
    #returns the magnitude and direction in a nicely printed format 
    #"The magnitude of a + b is X and the direction is Y"
    
    a_size = a.size
    b_size = b.size
    
    try:
        #check vectors are of same size
        a_size == b_size
        
        #calculate direction
        a_b_sum = a + b
        
        #calcualte magnitude of resulant direction vector
        magnitude = np.linalg.norm(a_b_sum)
        
        print('The magnitude of a+b is {} and the direction is {}'.format(magnitude, a_b_sum))
    
    except:
        print('Vectors are different dimensions {} and {}'.format(a_size, b_size))
    

In [14]:
magdir_vectors(a, b)

The magnitude of a+b is 1.0 and the direction is [1 0]


Video pt. 4: https://www.loom.com/share/ca3b43aea7b644e586d400df5f2b7bbb 

![title](./img/1_4.png)
- What is the magnitude of αx?
    - magnitude is $\sqrt{(alpha * a) ^2 + (alpha * b)^2}$
- If α>0, will the direction of the resulting vector change?
    - Vector will maintain its direction.
- If α<0, will the direction of the resulting vector change?
    - Vector will change direction
- If −1<α<1, will ∥αx∥  increase, decrease or stay the same?
    - ∥αx∥ will be the same for equal magnitues of positve and negative scalars. i.e. ∥αx∥ isthe same for alpha =1 and alpha = -1
    

Video pt. 5: https://www.loom.com/share/ba94138ed817499faeec76ed6b827bf2
Video pt. 6: https://www.loom.com/share/45eca4576fa547c2a7bb8b77b8eada3c

In [12]:
import numpy as np
def alpha_magnitude(alpha, b):
    #returns the resulting magnitude, if the direction has changed and what has happened to the vector
    b = np.array(b)
    vector = alpha * b
    if np.sign(b[0]) == np.sign(vector[0]):
        print('No directional change')
    else:
        print('The direction has changed 180 degrees')
    return (vector,  np.linalg.norm(vector))
    
    

In [13]:
alpha_magnitude(-8, [1,1])

The direction has changed 180 degrees


(array([-8, -8]), 11.313708498984761)

In [8]:
alpha_magnitude(5, [1,1])

No directional change


(array([5, 5]), 7.0710678118654755)

In [ ]:
[[1,0,0]
 [0,1,0]
 [0,0,1]]

