## Remember that the solutions need to be saved int variable provided.

In [1]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [2]:
# 1 point
sol1 = np.random.rand(10,10)
minim = sol1.min()
maxim = sol1.max()
print(minim, maxim)

0.007528007511574786 0.9667471753931111


In [3]:
assert sol1.shape == (10,10)

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [4]:
#1 points
sol2 = 0
sol2 = np.ones((10,10)).astype(int)
sol2[1:-1, 1:-1] = 0
sol2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [5]:
assert sol2.shape == (10,10)
assert sol2[0].all() == 1
assert sol2[:,0].all() == 1
assert sol2[1][1] == 0
assert sol2[2][2] == 0
assert sol2[3][3] == 0
assert sol2[4][4] == 0
assert sol2[1][2] == 0
assert sol2[2][3] == 0
assert sol2[3][4] == 0
assert sol2[4][5] == 0

**34. How to get all the dates corresponding to the month of July 2016**

In [6]:
#2 points
sol3 = 0
sol3 = np.arange("2016-07", "2016-08", dtype='datetime64[D]')
sol3


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [7]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [8]:
#2 points
sol41 = np.random.random((10,10))
sol42 = np.random.random((10,10))
comparisson = np.array_equal(sol41, sol42)
comparisson


False

In [9]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

TypeError: 'bool' object is not iterable

**72. How to swap two rows of an array?** 

In [ ]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])
sol5[[0,1]] = sol5[[1,0]]
sol5

array([[4, 5, 6],
       [1, 2, 3]])

In [ ]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = np.cumsum(arr) / np.size(arr)
sol6



array([0.1, 0.3, 0.6, 1. , 1.5, 2.1, 2.8, 3.6, 4.5, 5.5])

In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5

In [ ]:
a = [1,2,3]
b = np.array([1,2,3])
print(b+[4,5,6])

[5 7 9]


In [ ]:
arr = np.array([1,2,3,4,5,6])
ar1 = np.argwhere(arr%2==0).flatten()
arr[ar1]

array([2, 4, 6])